### ISSUE TITLE
Documentation mentions storage pool

### ISSUE THREAD

**Issue by jameinel** [canonical/grafana-operator#1]
https://github.com/canonical/grafana-operator/blob/master/README.md
currently says to create a storage pool:
juju create-storage-pool operator-storage kubernetes storage-class=microk8s-hostpath

however, it doesn't ever make use of that in the rest of the README.

**Comment by justinmclark** [comment]
This part of the README was inspired by a previous Grafana charm and I'm wondering if that line is even necessary anymore? I see this in the Juju docs:

> In v.2.6.0, upon invocation of add-k8s, automatic storage pool (as well as dynamic volume) configuration will be attempted. The manual creation of pools, therefore, may not be necessary.

**Comment by rbarry82** [comment]
No longer needed or part of `README.md`
